---
- name: Download and convert GPG keys in Debian OS
  block:
  
    # Download Kubernetes GPG key in ASCII format
    - name: Download Kubernetes GPG key in ASCII format
      ansible.builtin.get_url:
        url: "{{ k8_32_gpg_deb }}"
        dest: /tmp/kubernetes.gpg

    # Convert the downloaded Kubernetes GPG key to binary format and move it to the trusted keyring
    - name: Convert Kubernetes GPG key to binary and copy to /etc/apt/trusted.gpg.d
      ansible.builtin.command:
        cmd: gpg --dearmor -o /etc/apt/trusted.gpg.d/kubernetes-apt-keyring.gpg /tmp/kubernetes.gpg
        creates: /etc/apt/trusted.gpg.d/kubernetes-apt-keyring.gpg

    # Download Docker GPG key in ASCII format
    - name: Download Docker GPG key in ASCII format
      ansible.builtin.get_url:
        url: "{{ docker_gpg }}"
        dest: /tmp/containerd.gpg

    # Convert the downloaded Docker GPG key to binary format and move it to the trusted keyring
    - name: Convert Docker GPG key to binary and copy to /etc/apt/trusted.gpg.d
      ansible.builtin.command:
        cmd: gpg --dearmor -o /etc/apt/trusted.gpg.d/docker-archive-keyring.gpg /tmp/containerd.gpg
        creates: /etc/apt/trusted.gpg.d/docker-archive-keyring.gpg

  rescue:
    - name: Handle errors in downloading or converting GPG keys
      ansible.builtin.debug:
        msg: "Error downloading or converting GPG keys"

- name: Configure Kubernetes and Docker repositories
  block:
    # Add the Kubernetes repository to the sources list
    - name: Copy Kubernetes repository URL to /etc/apt/sources.list.d
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/kubernetes.list
        content: "deb [signed-by=/etc/apt/trusted.gpg.d/kubernetes-apt-keyring.gpg] {{ k8_32_repo_deb }}"

    # Add the Docker repository to the sources list
    - name: Copy Docker repository URL to /etc/apt/sources.list.d
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/docker.list
        content: "deb [signed-by=/etc/apt/trusted.gpg.d/docker-archive-keyring.gpg] {{ docker_repo }}"
      
  rescue:
    - name: Handle errors in repository configuration
      ansible.builtin.debug:
        msg: "Error configuring repositories"