# common/tasks/03-allow-ports-master.yml

- name: Enable firewalld if not active
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: yes
  when: ansible_os_family == "RedHat"

- name: Open required ports in firewalld
  ansible.posix.firewalld:
    port: "{{ item }}/tcp"
    permanent: yes
    state: enabled
  loop:
    - 6443
    - 2379-2380
    - 10250
    - 10259
    - 10257
    - 22
  when: ansible_os_family == "RedHat"

- name: Reload firewalld
  ansible.builtin.command: firewall-cmd --reload
  when: ansible_os_family == "RedHat"
    
- name: Ensure that iptables-persistent is installed
  ansible.builtin.apt:
    name: iptables-persistent
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Open ports in iptables
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ item }}"
    jump: ACCEPT
  loop:
    - 6443
    - 2379
    - 2380
    - 10250
    - 10259
    - 10257
    - 22
  when: ansible_os_family == "Debian"

- name: Save iptables rules
  ansible.builtin.command: netfilter-persistent save
  when: ansible_os_family == "Debian"