#SPDX-License-Identifier: MIT-0
---
# tasks file for common

- name: Load variables from repo_vars.yml
  include_vars:
    file: "../vars/main.yml"

- name: Include task to check connectivity
  ansible.builtin.include_tasks: 00-check-connectivity.yml

- name: Include task to add GPG keys and Repos (Debian)
  ansible.builtin.include_tasks: 01-repo-config-deb.yml
  when: ansible_os_family == "Debian"

- name: Include task to add GPG keys and Repos (RedHat)
  ansible.builtin.include_tasks: 02-repo-config-rh.yml
  when: ansible_os_family == "RedHat"

- name: Include task to allow Kubernetes Ports in Masters
  ansible.builtin.include_tasks: 03-allow-ports-master.yml
  when: "'k8-masters' in group_names"

- name: Include task to allow Kubernetes Ports in Workers
  ansible.builtin.include_tasks: 04-allow-ports-worker.yml
  when: "'k8-workers' in group_names"